collections:
  stuff:
    output: true
    permalink: /:title/

defaults:
#  - scope:
#      path: ''
#    values:
#      layout: 'page'
  - scope:
      path: ''
      type: 'stuff'
    values:
      layout: 'stuff'
